name: Style Audit

on:
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**/*.scss'
      - '**/*.css'
      - '.stylelintrc.json'
      - 'tools/style-audit.js'

jobs:
  style-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run style linting
        run: npm run lint-styles
        
      - name: Run full style audit
        run: npm run audit-styles
